//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectBAdminPanel.MyRestaurantService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserLoginControlModel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class UserLoginControlModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool LoginOkField;
        
        private int UserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SurnameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool LoginOk {
            get {
                return this.LoginOkField;
            }
            set {
                if ((this.LoginOkField.Equals(value) != true)) {
                    this.LoginOkField = value;
                    this.RaisePropertyChanged("LoginOk");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int UserType {
            get {
                return this.UserTypeField;
            }
            set {
                if ((this.UserTypeField.Equals(value) != true)) {
                    this.UserTypeField = value;
                    this.RaisePropertyChanged("UserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Surname {
            get {
                return this.SurnameField;
            }
            set {
                if ((object.ReferenceEquals(this.SurnameField, value) != true)) {
                    this.SurnameField = value;
                    this.RaisePropertyChanged("Surname");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuCategory", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MenuCategory : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductType {
            get {
                return this.ProductTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeField, value) != true)) {
                    this.ProductTypeField = value;
                    this.RaisePropertyChanged("ProductType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuProduct", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class MenuProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        private int ProductTypeIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductTypeNameField;
        
        private decimal PriceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ProductTypeId {
            get {
                return this.ProductTypeIdField;
            }
            set {
                if ((this.ProductTypeIdField.Equals(value) != true)) {
                    this.ProductTypeIdField = value;
                    this.RaisePropertyChanged("ProductTypeId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ProductTypeName {
            get {
                return this.ProductTypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductTypeNameField, value) != true)) {
                    this.ProductTypeNameField = value;
                    this.RaisePropertyChanged("ProductTypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MyRestaurantService.MyRestaurantServiceSoap")]
    public interface MyRestaurantServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUserControl", ReplyAction="*")]
        ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponse LoginUserControl(ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoginUserControl", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponse> LoginUserControlAsync(ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest request);
        
        // CODEGEN: Generating message contract since element name AllMenuCategoriesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllMenuCategories", ReplyAction="*")]
        ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponse AllMenuCategories(ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllMenuCategories", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponse> AllMenuCategoriesAsync(ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest request);
        
        // CODEGEN: Generating message contract since element name cat from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditMenuCategory", ReplyAction="*")]
        ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponse EditMenuCategory(ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditMenuCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponse> EditMenuCategoryAsync(ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name catName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMenuCategory", ReplyAction="*")]
        ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponse AddMenuCategory(ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMenuCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponse> AddMenuCategoryAsync(ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name AllProductsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllProducts", ReplyAction="*")]
        ProjectBAdminPanel.MyRestaurantService.AllProductsResponse AllProducts(ProjectBAdminPanel.MyRestaurantService.AllProductsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllProducts", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AllProductsResponse> AllProductsAsync(ProjectBAdminPanel.MyRestaurantService.AllProductsRequest request);
        
        // CODEGEN: Generating message contract since element name prd from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMenuProduct", ReplyAction="*")]
        ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponse AddMenuProduct(ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMenuProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponse> AddMenuProductAsync(ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserControlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUserControl", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequestBody Body;
        
        public LoginUserControlRequest() {
        }
        
        public LoginUserControlRequest(ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserControlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginUserControlRequestBody() {
        }
        
        public LoginUserControlRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginUserControlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginUserControlResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponseBody Body;
        
        public LoginUserControlResponse() {
        }
        
        public LoginUserControlResponse(ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginUserControlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.UserLoginControlModel LoginUserControlResult;
        
        public LoginUserControlResponseBody() {
        }
        
        public LoginUserControlResponseBody(ProjectBAdminPanel.MyRestaurantService.UserLoginControlModel LoginUserControlResult) {
            this.LoginUserControlResult = LoginUserControlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllMenuCategoriesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllMenuCategories", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequestBody Body;
        
        public AllMenuCategoriesRequest() {
        }
        
        public AllMenuCategoriesRequest(ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllMenuCategoriesRequestBody {
        
        public AllMenuCategoriesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllMenuCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllMenuCategoriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponseBody Body;
        
        public AllMenuCategoriesResponse() {
        }
        
        public AllMenuCategoriesResponse(ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllMenuCategoriesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.MenuCategory[] AllMenuCategoriesResult;
        
        public AllMenuCategoriesResponseBody() {
        }
        
        public AllMenuCategoriesResponseBody(ProjectBAdminPanel.MyRestaurantService.MenuCategory[] AllMenuCategoriesResult) {
            this.AllMenuCategoriesResult = AllMenuCategoriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMenuCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMenuCategory", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequestBody Body;
        
        public EditMenuCategoryRequest() {
        }
        
        public EditMenuCategoryRequest(ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditMenuCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.MenuCategory cat;
        
        public EditMenuCategoryRequestBody() {
        }
        
        public EditMenuCategoryRequestBody(ProjectBAdminPanel.MyRestaurantService.MenuCategory cat) {
            this.cat = cat;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EditMenuCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EditMenuCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponseBody Body;
        
        public EditMenuCategoryResponse() {
        }
        
        public EditMenuCategoryResponse(ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EditMenuCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int EditMenuCategoryResult;
        
        public EditMenuCategoryResponseBody() {
        }
        
        public EditMenuCategoryResponseBody(int EditMenuCategoryResult) {
            this.EditMenuCategoryResult = EditMenuCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMenuCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMenuCategory", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequestBody Body;
        
        public AddMenuCategoryRequest() {
        }
        
        public AddMenuCategoryRequest(ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMenuCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string catName;
        
        public AddMenuCategoryRequestBody() {
        }
        
        public AddMenuCategoryRequestBody(string catName) {
            this.catName = catName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMenuCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMenuCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponseBody Body;
        
        public AddMenuCategoryResponse() {
        }
        
        public AddMenuCategoryResponse(ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMenuCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddMenuCategoryResult;
        
        public AddMenuCategoryResponseBody() {
        }
        
        public AddMenuCategoryResponseBody(int AddMenuCategoryResult) {
            this.AddMenuCategoryResult = AddMenuCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllProductsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllProducts", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AllProductsRequestBody Body;
        
        public AllProductsRequest() {
        }
        
        public AllProductsRequest(ProjectBAdminPanel.MyRestaurantService.AllProductsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllProductsRequestBody {
        
        public AllProductsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllProductsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllProductsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AllProductsResponseBody Body;
        
        public AllProductsResponse() {
        }
        
        public AllProductsResponse(ProjectBAdminPanel.MyRestaurantService.AllProductsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllProductsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.MenuProduct[] AllProductsResult;
        
        public AllProductsResponseBody() {
        }
        
        public AllProductsResponseBody(ProjectBAdminPanel.MyRestaurantService.MenuProduct[] AllProductsResult) {
            this.AllProductsResult = AllProductsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMenuProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMenuProduct", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequestBody Body;
        
        public AddMenuProductRequest() {
        }
        
        public AddMenuProductRequest(ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMenuProductRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.MenuProduct prd;
        
        public AddMenuProductRequestBody() {
        }
        
        public AddMenuProductRequestBody(ProjectBAdminPanel.MyRestaurantService.MenuProduct prd) {
            this.prd = prd;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMenuProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMenuProductResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponseBody Body;
        
        public AddMenuProductResponse() {
        }
        
        public AddMenuProductResponse(ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMenuProductResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddMenuProductResult;
        
        public AddMenuProductResponseBody() {
        }
        
        public AddMenuProductResponseBody(int AddMenuProductResult) {
            this.AddMenuProductResult = AddMenuProductResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MyRestaurantServiceSoapChannel : ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MyRestaurantServiceSoapClient : System.ServiceModel.ClientBase<ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap>, ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap {
        
        public MyRestaurantServiceSoapClient() {
        }
        
        public MyRestaurantServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MyRestaurantServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyRestaurantServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MyRestaurantServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponse ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.LoginUserControl(ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest request) {
            return base.Channel.LoginUserControl(request);
        }
        
        public ProjectBAdminPanel.MyRestaurantService.UserLoginControlModel LoginUserControl(string userName, string password) {
            ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest inValue = new ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponse retVal = ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).LoginUserControl(inValue);
            return retVal.Body.LoginUserControlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponse> ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.LoginUserControlAsync(ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest request) {
            return base.Channel.LoginUserControlAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.LoginUserControlResponse> LoginUserControlAsync(string userName, string password) {
            ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest inValue = new ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.LoginUserControlRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).LoginUserControlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponse ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AllMenuCategories(ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest request) {
            return base.Channel.AllMenuCategories(request);
        }
        
        public ProjectBAdminPanel.MyRestaurantService.MenuCategory[] AllMenuCategories() {
            ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequestBody();
            ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponse retVal = ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AllMenuCategories(inValue);
            return retVal.Body.AllMenuCategoriesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponse> ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AllMenuCategoriesAsync(ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest request) {
            return base.Channel.AllMenuCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesResponse> AllMenuCategoriesAsync() {
            ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AllMenuCategoriesRequestBody();
            return ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AllMenuCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponse ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.EditMenuCategory(ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest request) {
            return base.Channel.EditMenuCategory(request);
        }
        
        public int EditMenuCategory(ProjectBAdminPanel.MyRestaurantService.MenuCategory cat) {
            ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest inValue = new ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequestBody();
            inValue.Body.cat = cat;
            ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponse retVal = ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).EditMenuCategory(inValue);
            return retVal.Body.EditMenuCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponse> ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.EditMenuCategoryAsync(ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest request) {
            return base.Channel.EditMenuCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryResponse> EditMenuCategoryAsync(ProjectBAdminPanel.MyRestaurantService.MenuCategory cat) {
            ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest inValue = new ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.EditMenuCategoryRequestBody();
            inValue.Body.cat = cat;
            return ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).EditMenuCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponse ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AddMenuCategory(ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest request) {
            return base.Channel.AddMenuCategory(request);
        }
        
        public int AddMenuCategory(string catName) {
            ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequestBody();
            inValue.Body.catName = catName;
            ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponse retVal = ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AddMenuCategory(inValue);
            return retVal.Body.AddMenuCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponse> ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AddMenuCategoryAsync(ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest request) {
            return base.Channel.AddMenuCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryResponse> AddMenuCategoryAsync(string catName) {
            ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AddMenuCategoryRequestBody();
            inValue.Body.catName = catName;
            return ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AddMenuCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBAdminPanel.MyRestaurantService.AllProductsResponse ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AllProducts(ProjectBAdminPanel.MyRestaurantService.AllProductsRequest request) {
            return base.Channel.AllProducts(request);
        }
        
        public ProjectBAdminPanel.MyRestaurantService.MenuProduct[] AllProducts() {
            ProjectBAdminPanel.MyRestaurantService.AllProductsRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AllProductsRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AllProductsRequestBody();
            ProjectBAdminPanel.MyRestaurantService.AllProductsResponse retVal = ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AllProducts(inValue);
            return retVal.Body.AllProductsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AllProductsResponse> ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AllProductsAsync(ProjectBAdminPanel.MyRestaurantService.AllProductsRequest request) {
            return base.Channel.AllProductsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AllProductsResponse> AllProductsAsync() {
            ProjectBAdminPanel.MyRestaurantService.AllProductsRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AllProductsRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AllProductsRequestBody();
            return ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AllProductsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponse ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AddMenuProduct(ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest request) {
            return base.Channel.AddMenuProduct(request);
        }
        
        public int AddMenuProduct(ProjectBAdminPanel.MyRestaurantService.MenuProduct prd) {
            ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequestBody();
            inValue.Body.prd = prd;
            ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponse retVal = ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AddMenuProduct(inValue);
            return retVal.Body.AddMenuProductResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponse> ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap.AddMenuProductAsync(ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest request) {
            return base.Channel.AddMenuProductAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProjectBAdminPanel.MyRestaurantService.AddMenuProductResponse> AddMenuProductAsync(ProjectBAdminPanel.MyRestaurantService.MenuProduct prd) {
            ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest inValue = new ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequest();
            inValue.Body = new ProjectBAdminPanel.MyRestaurantService.AddMenuProductRequestBody();
            inValue.Body.prd = prd;
            return ((ProjectBAdminPanel.MyRestaurantService.MyRestaurantServiceSoap)(this)).AddMenuProductAsync(inValue);
        }
    }
}
